--- #YAML:1.0
name:                DBIx-SQLite-Simple
version:             0.34
abstract:            easy access to SQLite databases using objects
license:             Artistic
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Class::Gomor:                  0
    DBD::SQLite:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - GomoR <perl@gomor.org>
