# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DBIx-SQLite-Simple
version:      0.32
version_from: lib/DBIx/SQLite/Simple.pm
installdirs:  site
requires:
    Class::Gomor:                  0
    DBD::SQLite:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
